
package fabrica.gestiondeproducciones.presentacion;

import fabrica.gestiondeproducciones.dominio.Controlador;
import fabrica.gestiondeproducciones.dominio.Empleado;
import fabrica.gestiondeproducciones.dominio.Insumo;
import fabrica.gestiondeproducciones.dominio.LechePasteurizada;
import fabrica.gestiondeproducciones.dominio.Produccion;
import fabrica.gestiondeproducciones.dominio.Producto;
import fabrica.gestiondeproducciones.persistencia.PersistenciaProduccion;
import fabrica.gestiondeproducciones.utilidades.Utilidades;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    
    public Principal() {
        initComponents();
   
    }
    
    // <editor-fold defaultstate="collapsed" desc="Singleton">
   private void Singleton(String pFormulario) {
    boolean encontrado = false;

    
    for (JInternalFrame frame : escritorio.getAllFrames()) {
        if (frame.getName().equals(pFormulario)) { // Usamos getName() en lugar de getTitle()
            encontrado = true;
            try {
                frame.setSelected(true); 
            } catch (Exception e) {
                e.printStackTrace();
            }
            break; // Detiene la búsqueda una vez encontrada
        }
    }

    
    if (!encontrado) {
        JInternalFrame nuevoFrame = null;

        switch (pFormulario) {
            case "GestionSilos":
                nuevoFrame = new GestionSilos();
                break;
            case "GestionAnalisisDulce":
                nuevoFrame = new GestionAnalisisDulce();
                break;
            case "GestionAnalisisLeche":
                nuevoFrame = new GestionAnalisisLeche();
                break;
            case "GestionAnalisisLechePasteurizada":
                nuevoFrame = new GestionAnalisisLechePasteurizada();
                break;    
            case "GestionAnalisisManteca":
                nuevoFrame = new GestionAnalisisManteca();
                break;
            case "GestionAnalisisQueso":
                nuevoFrame = new GestionAnalisisQueso();
                break;
            case "GestionAnalisisYogur":
                nuevoFrame = new GestionAnalisisYogur();
                break;
            case "GestionEmpleados":
                nuevoFrame = new GestionEmpleados();
                break;
            case "GestionEnvases":
                nuevoFrame = new GestionEnvases();
                break;
            case "GestionIngresoLeche":
                nuevoFrame = new GestionIngresoLeche();
                break;
            case "GestionInsumos":
                nuevoFrame = new GestionInsumos();
                break;
            case "GestionPasteurizados":
                nuevoFrame = new GestionPasteurizados();
                break;
            case "GestionProduccionDulce":
                nuevoFrame = new GestionProduccionDulce();
                break;    
            case "GestionProduccionManteca":
                nuevoFrame = new GestionProduccionManteca();
                break;
            case "GestionProduccionQueso":
                nuevoFrame = new GestionProduccionQueso();
                break;    
            case "GestionProduccionYogur":
                nuevoFrame = new GestionProduccionYogur();
                break;
            case "GestionProductos":
                nuevoFrame = new GestionProductos();
                break;
            case "GestionSecciones":
                nuevoFrame = new GestionSecciones();
                break;
            case "GestionTambo":
                nuevoFrame = new GestionTambo();
                break;
            case "ListadoAnalisis":
                nuevoFrame = new ListadoAnalisis();
                break;
        }

        if (nuevoFrame != null) {
            nuevoFrame.setName(pFormulario); // Establece un nombre para comparación
            escritorio.add(nuevoFrame);
            nuevoFrame.setVisible(true);
        }
    }
}// </editor-fold>  



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuSilos = new javax.swing.JMenu();
        menuSecciones = new javax.swing.JMenu();
        menuTambos = new javax.swing.JMenu();
        menuInsumos = new javax.swing.JMenu();
        menuEmpleados = new javax.swing.JMenu();
        menuLeche = new javax.swing.JMenu();
        menuIngresos = new javax.swing.JMenuItem();
        menuPasteurizados = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuAnalisisLeche = new javax.swing.JMenuItem();
        menuAnalisisLechePasteurizada = new javax.swing.JMenuItem();
        menuAnalisisManteca = new javax.swing.JMenuItem();
        menuAnalisisYogur = new javax.swing.JMenuItem();
        menuAnalisisQueso = new javax.swing.JMenuItem();
        menuAnalisisDulce = new javax.swing.JMenuItem();
        jMenuProducciones = new javax.swing.JMenu();
        menuProduccionesManteca = new javax.swing.JMenuItem();
        menuProduccionYogur = new javax.swing.JMenuItem();
        menuProduccionQueso = new javax.swing.JMenuItem();
        menuProduccionDulce = new javax.swing.JMenuItem();
        menuEnvases = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuAnalisis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        menuSilos.setText("Silos");
        menuSilos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSilosMouseClicked(evt);
            }
        });
        menuSilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSilosActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuSilos);

        menuSecciones.setText("Secciones");
        menuSecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSeccionesMouseClicked(evt);
            }
        });
        menuSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSeccionesActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuSecciones);

        menuTambos.setText("Tambos");
        menuTambos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTambosMouseClicked(evt);
            }
        });
        menuTambos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambosActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuTambos);

        menuInsumos.setText("Insumos");
        menuInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInsumosMouseClicked(evt);
            }
        });
        menuPrincipal.add(menuInsumos);

        menuEmpleados.setText("Empleados");
        menuEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEmpleadosMouseClicked(evt);
            }
        });
        menuPrincipal.add(menuEmpleados);

        menuLeche.setText("Leche");

        menuIngresos.setText("Ingresos de Leche");
        menuIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresosActionPerformed(evt);
            }
        });
        menuLeche.add(menuIngresos);

        menuPasteurizados.setText("Pasteurizar Leche");
        menuPasteurizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPasteurizadosActionPerformed(evt);
            }
        });
        menuLeche.add(menuPasteurizados);

        menuPrincipal.add(menuLeche);

        jMenu1.setText("Analisis");

        menuAnalisisLeche.setText("Analisis de Leche");
        menuAnalisisLeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnalisisLecheActionPerformed(evt);
            }
        });
        jMenu1.add(menuAnalisisLeche);

        menuAnalisisLechePasteurizada.setText("Analisis de Leche Pasteurizada");
        menuAnalisisLechePasteurizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnalisisLechePasteurizadaActionPerformed(evt);
            }
        });
        jMenu1.add(menuAnalisisLechePasteurizada);

        menuAnalisisManteca.setText("Analisis de Manteca");
        menuAnalisisManteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnalisisMantecaActionPerformed(evt);
            }
        });
        jMenu1.add(menuAnalisisManteca);

        menuAnalisisYogur.setText("Analisis de Yogur");
        menuAnalisisYogur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnalisisYogurActionPerformed(evt);
            }
        });
        jMenu1.add(menuAnalisisYogur);

        menuAnalisisQueso.setText("Analisis de Queso");
        menuAnalisisQueso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnalisisQuesoActionPerformed(evt);
            }
        });
        jMenu1.add(menuAnalisisQueso);

        menuAnalisisDulce.setText("Analisis de Dulce");
        menuAnalisisDulce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnalisisDulceActionPerformed(evt);
            }
        });
        jMenu1.add(menuAnalisisDulce);

        menuPrincipal.add(jMenu1);

        jMenuProducciones.setText("Producciones");

        menuProduccionesManteca.setText("Produccion de Manteca");
        menuProduccionesManteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProduccionesMantecaActionPerformed(evt);
            }
        });
        jMenuProducciones.add(menuProduccionesManteca);

        menuProduccionYogur.setText("Produccion de Yogur");
        menuProduccionYogur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProduccionYogurActionPerformed(evt);
            }
        });
        jMenuProducciones.add(menuProduccionYogur);

        menuProduccionQueso.setText("Produccion de Queso");
        menuProduccionQueso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProduccionQuesoActionPerformed(evt);
            }
        });
        jMenuProducciones.add(menuProduccionQueso);

        menuProduccionDulce.setText("Produccion de Dulce");
        menuProduccionDulce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProduccionDulceActionPerformed(evt);
            }
        });
        jMenuProducciones.add(menuProduccionDulce);

        menuPrincipal.add(jMenuProducciones);

        menuEnvases.setText("Envases Dulce");
        menuEnvases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEnvasesMouseClicked(evt);
            }
        });
        menuPrincipal.add(menuEnvases);

        jMenu2.setText("Listados");

        menuAnalisis.setText("Analisis");
        menuAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnalisisActionPerformed(evt);
            }
        });
        jMenu2.add(menuAnalisis);

        menuPrincipal.add(jMenu2);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(escritorio))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSilosActionPerformed

    }//GEN-LAST:event_menuSilosActionPerformed

    private void menuSilosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSilosMouseClicked
        this.Singleton("GestionSilos");
    }//GEN-LAST:event_menuSilosMouseClicked

    private void menuSeccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSeccionesMouseClicked
        this.Singleton("GestionSecciones");
    }//GEN-LAST:event_menuSeccionesMouseClicked

    private void menuSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSeccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSeccionesActionPerformed

    private void menuTambosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTambosMouseClicked
       this.Singleton("GestionTambo");
    }//GEN-LAST:event_menuTambosMouseClicked

    private void menuTambosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuTambosActionPerformed

    private void menuInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInsumosMouseClicked
       this.Singleton("GestionInsumos");
    }//GEN-LAST:event_menuInsumosMouseClicked

    private void menuEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmpleadosMouseClicked
        this.Singleton("GestionEmpleados");
    }//GEN-LAST:event_menuEmpleadosMouseClicked

    private void menuIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresosActionPerformed
        this.Singleton("GestionIngresoLeche");
    }//GEN-LAST:event_menuIngresosActionPerformed

    private void menuPasteurizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPasteurizadosActionPerformed
        this.Singleton("GestionPasteurizados");
    }//GEN-LAST:event_menuPasteurizadosActionPerformed

    private void menuAnalisisLecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnalisisLecheActionPerformed
        this.Singleton("GestionAnalisisLeche");
    }//GEN-LAST:event_menuAnalisisLecheActionPerformed

    private void menuAnalisisLechePasteurizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnalisisLechePasteurizadaActionPerformed
       this.Singleton("GestionAnalisisLechePasteurizada");
    }//GEN-LAST:event_menuAnalisisLechePasteurizadaActionPerformed

    private void menuProduccionesMantecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProduccionesMantecaActionPerformed
        this.Singleton("GestionProduccionManteca");
    }//GEN-LAST:event_menuProduccionesMantecaActionPerformed

    private void menuProduccionYogurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProduccionYogurActionPerformed
        this.Singleton("GestionProduccionYogur");
    }//GEN-LAST:event_menuProduccionYogurActionPerformed

    private void menuAnalisisMantecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnalisisMantecaActionPerformed
        this.Singleton("GestionAnalisisManteca");
    }//GEN-LAST:event_menuAnalisisMantecaActionPerformed

    private void menuProduccionQuesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProduccionQuesoActionPerformed
       this.Singleton("GestionProduccionQueso");
    }//GEN-LAST:event_menuProduccionQuesoActionPerformed

    private void menuAnalisisYogurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnalisisYogurActionPerformed
        this.Singleton("GestionAnalisisYogur");
    }//GEN-LAST:event_menuAnalisisYogurActionPerformed

    private void menuAnalisisQuesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnalisisQuesoActionPerformed
        this.Singleton("GestionAnalisisQueso");
    }//GEN-LAST:event_menuAnalisisQuesoActionPerformed

    private void menuEnvasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEnvasesMouseClicked
       this.Singleton("GestionEnvases");
    }//GEN-LAST:event_menuEnvasesMouseClicked

    private void menuProduccionDulceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProduccionDulceActionPerformed
       this.Singleton("GestionProduccionDulce");
    }//GEN-LAST:event_menuProduccionDulceActionPerformed

    private void menuAnalisisDulceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnalisisDulceActionPerformed
        this.Singleton("GestionAnalisisDulce");
    }//GEN-LAST:event_menuAnalisisDulceActionPerformed

    private void menuAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnalisisActionPerformed
        this.Singleton("ListadoAnalisis");
    }//GEN-LAST:event_menuAnalisisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuProducciones;
    private javax.swing.JMenuItem menuAnalisis;
    private javax.swing.JMenuItem menuAnalisisDulce;
    private javax.swing.JMenuItem menuAnalisisLeche;
    private javax.swing.JMenuItem menuAnalisisLechePasteurizada;
    private javax.swing.JMenuItem menuAnalisisManteca;
    private javax.swing.JMenuItem menuAnalisisQueso;
    private javax.swing.JMenuItem menuAnalisisYogur;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenu menuEnvases;
    private javax.swing.JMenuItem menuIngresos;
    private javax.swing.JMenu menuInsumos;
    private javax.swing.JMenu menuLeche;
    private javax.swing.JMenuItem menuPasteurizados;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem menuProduccionDulce;
    private javax.swing.JMenuItem menuProduccionQueso;
    private javax.swing.JMenuItem menuProduccionYogur;
    private javax.swing.JMenuItem menuProduccionesManteca;
    private javax.swing.JMenu menuSecciones;
    private javax.swing.JMenu menuSilos;
    private javax.swing.JMenu menuTambos;
    // End of variables declaration//GEN-END:variables


}
